packages:
  - "."

autoInstallPeers: false
engineStrict: true
saveExact: true
strictPeerDependencies: false

allowBuilds:
  "@swc/core": true
  esbuild: true

minimumReleaseAgeExclude:
  - "@a-novel-kit/nodelib-config@1.10.0"
  - "@a-novel-kit/nodelib-browser@1.10.0"
  - "@a-novel-kit/nodelib-i18n@1.10.0"
  - "@a-novel-kit/nodelib-server@1.10.0"
  - "@a-novel-kit/uikit-fonts@0.6.7"
  - "@a-novel-kit/uikit-storybook@0.6.7"
  - "@a-novel-kit/uikit-tokens@0.6.7"
  - "@a-novel-kit/uikit@0.6.7"
  - "@a-novel-kit/uikit-images@0.6.7"
  - "@a-novel/service-authentication-rest@2.10.0"
  - "@a-novel-kit/nodelib-test@1.10.0"
