packages:
  - "."

autoInstallPeers: false
engineStrict: true
saveExact: true
strictPeerDependencies: false

allowBuilds:
  "@swc/core": true
  esbuild: true

minimumReleaseAgeExclude:
  - "@a-novel-kit/nodelib-config@1.6.3"
  - "@a-novel-kit/nodelib-browser@1.6.3"
  - "@a-novel-kit/nodelib-i18n@1.6.3"
  - "@a-novel-kit/nodelib-server@1.6.3"
  - "@a-novel-kit/uikit-fonts@0.3.0"
  - "@a-novel-kit/uikit-storybook@0.3.0"
  - "@a-novel-kit/uikit-tokens@0.3.0"
  - "@a-novel-kit/uikit@0.3.0"
