name: run renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: a-novel-kit/workflows/generic-actions/renovate@de35fd0061ce63c0184738d50dd3367ba5c0fb4b
        with:
          repository_config: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          client_id: ${{ vars.DEPENDENCY_BOT_CLIENT_ID }}
