name: visual-tests
run-name: Visual approval ${{ github.event.pull_request.number }} ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.ref }} ${{ github.event.action }}

on:
  workflow_run:
    workflows: [main]
    types: [completed]
  pull_request_target:
    types: [labeled, unlabeled, synchronize, opened, reopened, closed]
  delete:
  schedule:
    - cron: "23 4 * * *"

jobs:
  approval:
    if: ${{ github.event_name == 'pull_request_target' && vars.VISUAL_CI_PROVIDER != '' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 25
    concurrency:
      group: visual-approval-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    permissions:
      contents: read
      actions: write
      statuses: write
      pull-requests: read
    steps:
      - uses: a-novel-kit/workflows/generic-actions/approve-playwright@v1.36.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    if: ${{ vars.VISUAL_MAINTENANCE_PROVIDER != '' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    concurrency:
      group: visual-maintenance
      cancel-in-progress: false
    permissions:
      contents: read
      actions: read
      pull-requests: read
      id-token: write
    steps:
      - uses: a-novel-kit/workflows/generic-actions/maintain-playwright@v1.36.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          identity_provider: ${{ vars.VISUAL_MAINTENANCE_PROVIDER }}
          service_account: ${{ vars.VISUAL_MAINTENANCE_ACCOUNT }}
          references_folder: ${{ vars.VISUAL_REFERENCES_FOLDER }}
          results_folder: ${{ vars.VISUAL_RESULTS_FOLDER }}
